package cu.thunder.ai.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Original Yamin
val primaryLight = Color(0xFF2A6C14)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFACF68D)
val onPrimaryContainerLight = Color(0xFF042100)
val secondaryLight = Color(0xFF006397)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE5FF)
val onSecondaryContainerLight = Color(0xFF001D31)
val tertiaryLight = Color(0xFF9C404B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDADB)
val onTertiaryContainerLight = Color(0xFF40000E)
val backgroundLight = Color(0xFFF5FFF3)
val onBackgroundLight = Color(0xFF00210E)
val surfaceLight = Color(0xFFF5FFF3)
val onSurfaceLight = Color(0xFF00210E)
val surfaceVariantLight = Color(0xFFDFE4D7)
val onSurfaceVariantLight = Color(0xFF43483F)
val outlineLight = Color(0xFF73796E)
val errorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)

// Dark Theme - Original Yamin
val primaryDark = Color(0xFF91D974)
val onPrimaryDark = Color(0xFF0B3900)
val primaryContainerDark = Color(0xFF145200)
val onPrimaryContainerDark = Color(0xFFACF68D)
val secondaryDark = Color(0xFF92CCFF)
val onSecondaryDark = Color(0xFF003351)
val secondaryContainerDark = Color(0xFF004B73)
val onSecondaryContainerDark = Color(0xFFCCE5FF)
val tertiaryDark = Color(0xFFFFB2B7)
val onTertiaryDark = Color(0xFF5F1220)
val tertiaryContainerDark = Color(0xFF7D2935)
val onTertiaryContainerDark = Color(0xFFFFDADB)
val backgroundDark = Color(0xFF00210E)
val onBackgroundDark = Color(0xFF99F7B5)
val surfaceDark = Color(0xFF00210E)
val onSurfaceDark = Color(0xFF99F7B5)
val surfaceVariantDark = Color(0xFF43483F)
val onSurfaceVariantDark = Color(0xFFC3C8BB)
val outlineDark = Color(0xFF8D9387)
val errorDark = Color(0xFFFFB4AB)
val errorContainerDark = Color(0xFF93000A)