package cu.thunder.ai.ui.theme

import androidx.compose.ui.graphics.Color

// Telegram Blue Palette
val TelegramBlue = Color(0xFF3390EC)
val TelegramBlueLight = Color(0xFF64B5F6)
val TelegramBlueGrey = Color(0xFF4C7599)
val TelegramCyan = Color(0xFF00ACC1)
val TelegramCyanLight = Color(0xFF4DD0E1)

// Light Theme
val primaryLight = Color(0xFF3390EC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE3F2FD)
val onPrimaryContainerLight = Color(0xFF001D36)
val secondaryLight = Color(0xFF4C7599)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE3F2FD)
val onSecondaryContainerLight = Color(0xFF001D36)
val tertiaryLight = Color(0xFF00ACC1)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0F7FA)
val onTertiaryContainerLight = Color(0xFF00363C)
val backgroundLight = Color(0xFFFAFAFA)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFF1F3F4)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF74777F)
val errorLight = Color(0xFFBA1A1A)
val errorContainerLight = Color(0xFFFFDAD6)

// Dark Theme
val primaryDark = Color(0xFF64B5F6)
val onPrimaryDark = Color(0xFF001D36)
val primaryContainerDark = Color(0xFF0D47A1)
val onPrimaryContainerDark = Color(0xFFE3F2FD)
val secondaryDark = Color(0xFF81A9CA)
val onSecondaryDark = Color(0xFF001D36)
val secondaryContainerDark = Color(0xFF1A3A5C)
val onSecondaryContainerDark = Color(0xFFE3F2FD)
val tertiaryDark = Color(0xFF4DD0E1)
val onTertiaryDark = Color(0xFF00363C)
val tertiaryContainerDark = Color(0xFF006064)
val onTertiaryContainerDark = Color(0xFFE0F7FA)
val backgroundDark = Color(0xFF0F1A24)
val onBackgroundDark = Color(0xFFE3F2FD)
val surfaceDark = Color(0xFF162230)
val onSurfaceDark = Color(0xFFE3F2FD)
val surfaceVariantDark = Color(0xFF1E3448)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val errorDark = Color(0xFFFFB4AB)
val errorContainerDark = Color(0xFF93000A)